language: java
jdk:
  - oraclejdk13
env:
  - MAVEN_VERSION=3.3.9
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode -Prun-its clean verify"
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: mysenditapp